# -*- coding: utf-8 -*-
"""loader_real_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fnJOcT5U5sypmOvOEdVjQEVlxCU_XJI6
"""

!python -m pip install mysql-connector-python
!python -m pip install pymysql
import pymysql
import pandas as pd


connection_params = {
    'host': "certideal-db-data-analyst.cdlw37pka1gu.eu-west-1.rds.amazonaws.com",
    'user': "manel",
    'password': "CYzBJQcu8V+#",
    'database': "valco",
}

request = """
SELECT
DATE(o.date_add) AS date,
od.product_id AS id_product,
cl.name AS category,
fvcal.value AS capacity,
fvcol.value AS color,
fvstl.value AS state,
p.price,
SUM(od.product_quantity) AS quantity
FROM
ps_orders o
LEFT JOIN ps_order_detail od ON
o.id_order = od.id_order
LEFT JOIN ps_product p ON
od.product_id = p.id_product
LEFT JOIN ps_product_lang b ON
(b.id_product = p.id_product
AND b.id_lang = 1
AND b.id_shop = p.id_shop_default)
JOIN ps_product_shop sa ON
(p.id_product = sa.id_product
AND sa.id_shop = p.id_shop_default)
LEFT JOIN ps_category_lang cl ON
(sa.id_category_default = cl.id_category
AND b.id_lang = cl.id_lang
AND cl.id_shop = p.id_shop_default)
LEFT JOIN ps_feature_product fpst ON
(p.id_product = fpst.id_product
AND fpst.id_feature = 8)
LEFT JOIN ps_feature_value_lang fvstl ON
(fpst.id_feature_value = fvstl.id_feature_value
AND fvstl.id_lang = 1)
LEFT JOIN ps_feature_product fpca ON
(p.id_product = fpca.id_product
AND fpca.id_feature = 7)
LEFT JOIN ps_feature_value_lang fvcal ON
(fpca.id_feature_value = fvcal.id_feature_value
AND fvcal.id_lang = 1)
LEFT JOIN ps_feature_product fpco ON
(p.id_product = fpco.id_product
AND fpco.id_feature = 10)
LEFT JOIN ps_feature_value_lang fvcol ON
(fpco.id_feature_value = fvcol.id_feature_value
AND fvcol.id_lang = 1)
WHERE
DATE(o.date_add)  > now() - INTERVAL 3 MONTH
AND o.id_shop = 1
AND o.current_state = 4
AND cl.name LIKE '%iPhone%'
GROUP BY
od.product_id ,
o.id_shop ,
date
ORDER BY
date ,
o.id_shop ,
od.product_id;

"""

db  = pymysql.connect(**connection_params)
pd.read_sql_query(request,db).to_csv('Data_brute.csv')
